# build.yaml (optional, but good for managing build arguments)

build_from:
  aarch64: "homeassistant/aarch64-base-python:3.11-alpine3.18"
  amd64: "homeassistant/amd64-base-python:3.11-alpine3.18"
  armv7: "homeassistant/armv7-base-python:3.11-alpine3.18"
  armhf: "homeassistant/armhf-base-python:3.11-alpine3.18" # Usually same as armv7
  i386: "homeassistant/i386-base-python:3.11-alpine3.18"
# backend/requirements.txt
# List your Python dependencies here, one per line.

Flask>=2.0
requests>=2.25 # For making HTTP requests (e.g., to AI APIs or HA API)
# openai>=1.0 # If using the OpenAI Python library
# Pillow>=9.0 # For image manipulation, if needed
# numpy # If doing any numerical processing with images

# For now, just Flask is enough for the basic backend.
# Add more as you develop features.